### ISSUE TITLE
Produce figures, tables

### ISSUE THREAD

**Issue by ethanumn** [ethanumn/mpn-aml-pairtree#2]
**TODO**
- [ ] Verify with stakeholders which data is most important/relevant to research
- [ ] Determine list of how best to represent the results from the analysis (what type of figures, tables, etc.)
- [ ] Produce figures and tables, and verify axes, column headers, etc.
- [ ] Modify/update figures and tables based off of stakeholder feedback
