### ISSUE TITLE
Build trees

### ISSUE THREAD

**Issue by ethanumn** [ethanumn/mpn-aml-pairtree#3]
**TODO**
- [x] Build trees based off of subclone mutation clusters
- [x] Visualize and interpret trees to ensure they make sense
- [x] Run different configurations of pairtree with pairwise and linear frequency cluster, LOH methods, etc.
- [x] Run paitree using LOH method setting omega to 1 for those marked as LOH, both clustering methods, 50 cell count, use all samples, drop in slack (calling this strategy 7 based off of previous 8 trials
