### ISSUE TITLE
Deliverables post meeting (6/24/21)

### ISSUE THREAD

**Issue by ethanumn** [ethanumn/mpn-aml-pairtree#7]
**TODO**

- [x] Generate table with the following columns {sample name, # variants in primary xls, # of variants in calls xls, # variants imputed, total number of variants in sample}
- [x] Generate a table with a list of variants with VAF > 0.5
- [x] Generate a table with a list of variants pulled from the calls xls that have non-trivial VAFS

**Comment by ethanumn** [comment]
_Notes from meeting:_

- 8 patients who's data we'll be receiving
- Primary xls has CNA affected variants removed
- Used control to distinguish germline vs. somtaic. Used T cells as control during WGS
- Some variants may have been lost since some somatic mutations can be in T cells. None of these variants are germ-line but may be germ-line variants if they were driver genes.
- Used a software package to run copy number analysis
- Population of samples is not 100% clone of interest. Samples may be heterogenous. 
- Samples may need to be thrown out i they're missing a lot of variants
- JAK 2 variant on chr 9, V6171F has LOH
- Spotty covered may be due to bad DNA quality, may need to throw these samples out.
- May need to scale down counts to account for amplification bias from ddPCR. Divide by fixed number to scale up variance with respect to mean
- Goal of analysis is to determine the original cell type for a given mutation
