### ISSUE TITLE
Write .ssm file modifier

### ISSUE THREAD

**Issue by ethanumn** [ethanumn/mpn-aml-pairtree#8]
**TODO**

- [x] Allow scaling of total_reads and var_reads on a per variant/sample basis by a factor (_f = 1/(total_reads/scale)_ where _scale_ is an integer value that represents the maximum value for total_reads
- [x] Allow reorganizing of variants by VAF
- [x] Allow deletion of variants  by VAF
- [x] Allow scaling to be based off of a vector which represents cell counts per sample, where the scaling factor is applied on a per sample basis (_scale = 2 * cell_count_)
